version: '3.8'
services:
  server:
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    build: server
    network_mode: "host"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      - .env
